### PR TITLE
Subs landing banner and layout tweaks

### PR DESCRIPTION
**Pull request by jesseyuen**
## Why are you doing this?

The subs landing page layout looked a bit broken after the new nav was added. The subs landing is not on the new template so the fixes will be enough to make the layout feel more _coherent_ whilst avoiding a significant refractor. I've tried to be unobtrusive as possible so hopefully haven't broken anything else  

It's still not quite perfect but looks a lot better and I think it will help until we eventually redesign and move this page onto the new template.

P.S. - I'm only interested in fixing alignment in the **UK banner** at this stage. 

P.P.S - My commit messages are a bit vaguer than I wanted them to be, sorry. 

[**Trello Card**](https://trello.com/c/hvM44uZc/2220-subs-landing-layout-needs-adjustment)

## Changes

* Padding/width changes to the subs landing her panel
* Type updates on the headings in the banner to align with updated font sizes
* Minor padding updates to general containers to assist in new nav alignment

## Screenshots

**Before**

screen shot 2019-02-08 at 10 05 00

**After**

screen shot 2019-02-08 at 10 04 51

### CODE REVIEW

**Comment by walaura** [comment]
i think the rest of the banners are gonna carry the changes too so worth testing them! (they should be okay tho)

**Comment by walaura** [comment]
can't review today although i think this is an amazing change and should totally go live and you should persuade whoever you can to review this today – that said could you do me a massive favour and replace `LinkCta` in the banner with `Button`?

**Comment by jesseyuen** [comment]
> i think the rest of the banners are gonna carry the changes too so worth testing them! (they should be okay tho)

Paparazzi output looks good as did a quick test :)

**Comment by jesseyuen** [comment]
> that said could you do me a massive favour and replace `LinkCta` in the banner with `Button`

I don't know what this means :(

**Comment by SarahLaughton** [comment]
Love it!

**Comment by walaura** [comment]
> > that said could you do me a massive favour and replace `LinkCta` in the banner with `Button`
> 
> I don't totally get what this means :( Let's look at this part on Monday?

I'm on a workshop :( basically i meant could you replace the CTA button in the main header with the new buttons we use everywhere? it's one of the last places where that one is around! I don't think it needs to be done in this pr however

**Pull request merged**
