### PR TITLE
Set up first mobile optimisation test for the supporter plus checkout

### PR DESCRIPTION
**Pull request by i-hardy**
## What are you doing in this PR?

This PR sets up the first mobile optimisation test. I've also refactored a few components used in the checkout that were relevant to the test to make them a little more flexible and easier to apply conditional styling to.

[**Trello Card**](https://trello.com/c/zdqCSfuk)

## Why are you doing this?

This test aims to start to streamline the user flow on mobile.

## Accessibility test checklist
 - [x] [Tested with screen reader](https://webaim.org/articles/voiceover/)
 - [x] [Navigable with keyboard](https://www.accessibility-developer-guide.com/knowledge/keyboard-only/browsing-websites/)
 - [x] [Colour contrast passed](https://www.whocanuse.com/)

## Screenshots
Screenshot 2023-02-22 at 10-57-53 Support the Guardian

### CODE REVIEW

**Review by marialani — APPROVED** [review]
Looking good!

**Comment by marialani** [comment]
Only note from me on this might be on styling but is more whether we want to lean towards using [static vs dynamic styles](https://emotion.sh/docs/best-practices#use-the-style-prop-for-dynamic-styles) with the css prop on support frontend in future. We could discuss briefly at the catch up!

**Comment by GHaberis** [comment]
@i-hardy just letting you know @paul-daniel-dempsey removed his restriction on the current `singleToRecurringV3` test last week = so we could get learnings on all breakpoints for as long as possible (see https://github.com/guardian/support-frontend/pull/4805). The restriction will need to be restored once your test goes live, it may be easiest to add it in this PR?

**Review by paul-daniel-dempsey — APPROVED** [review]
All good too

**Pull request merged**
