### PR TITLE
rename AdminSettingsSource to SettingsSource

### PR DESCRIPTION
**Pull request by Mullefa**
## Why are you doing this?

Have `Settings` be consistent with `AdminSettingsSource`. Although given that there aren't multiple settings types how do people instead feel about renaming `AdminSettingsSource` to just `SettingsSource`?

I feel like one of the two should happen...

### CODE REVIEW

**Comment by rupertbates** [comment]
I think I would go with renaming `AdminSettingsSource`, I don't feel like the 'Admin' part is bringing much to the party

**Comment by joelochlann** [comment]
Yep, I agree with @rupertbates - I'd go with your second option. And also rename the config key `adminSettingsSource` -> `settingsSource`

**Comment by Mullefa** [comment]
My preference too. Will make the changes. Thanks for the input.

**Comment by Mullefa** [comment]
Additional benefit - simplified diff 🙌

**Pull request merged**
