### PR TITLE
WIP - do not deploy - Implement tip for stripe

### PR DESCRIPTION
**Pull request by michaelwmcnamara**
This is a follow up to https://github.com/guardian/support-frontend/pull/1004

This PR enables Tip tracking for: 
One-off Stripe payments in US, GB and AU
Monthly Stripe payments in US, GB and AU
Monthly Paypal payments in US, GB and AU
Annual Stripe payments in GB
In theory it also tracks one-off and monthly direct debit payments in GB

Other Annual payment types should be trackable by simply adding them to the tip.yaml file.

While one-off paypal payments could be implemented from the server-side,
Stripe payments do not provide enough information to the server side for the tip tool to be of any use.

As a result, this change creates an end-point to be hit from client side when a payment is successful. This endpoint provides the needed data to update TIP.

image

### CODE REVIEW

**Comment by michaelwmcnamara** [comment]
Do not merge without @jacobwinch's approval. This is an experimental branch and the approach used is still under discussion.

**Comment by michaelwmcnamara** [comment]
Note: Scalastyle max line length increased to 170 to allow for Monitoring trait to be included in Controller definition.
The reason for this is that compiling removed any splitting of this definition between lines and it was then impossible to build on team-city.

**Comment by johnduffell** [comment]
a lot of conflicts here! is this PR waiting for something or just abandoned?

**Comment by akash1810** [comment]
@michaelwmcnamara cc @guardian/reader-revenue shall we close or update this old WIP PR?

**Comment by jacobwinch** [comment]
A lot of this work has been incorporated into: https://github.com/guardian/support-frontend/pull/1123, https://github.com/guardian/support-frontend/pull/1160 and https://github.com/guardian/support-frontend/pull/1253 so I think this PR can be closed.

**Pull request closed without merging**
