### PR TITLE
BigQueryService: close resources, test everything

### PR DESCRIPTION
**Pull request by undergroundquizscene**
# Change Description

In commit fc82dde5c51f863f7c8d1c479592204ba4390389, I began closing resources after each request. However, while the acquisition-events-api can handle this, the payment-api can’t! The former creates a new service on every request, but the latter doesn’t, so on the first request the client was closed and never reopened, causing single contributions to break. (These changes were reverted in commit 6dbcd65e785a0498adbe9d0cc709d6a6fa8760a4).

This commit moves the closing logic so the payment-api doesn’t close the big query client after the first request, while the acquisition-events-api can still close and re-open on every request.

Another option would’ve been to create a new service on every request to the payment api, but the storage write api seems designed to be used in more of a long-running server context like this.

support-workers doesn’t create a new BigQueryService every time it runs, so I can’t close the stream writer and client after each run like I have done in the acquisition-events-api. Instead I’ve chosen to leave them open: when the underlying JVM/server shuts down the resources will hopefully be reclaimed, and on lambda cold start a new service will be created.

# PR Context

I’ve merged a version of these changes twice now, in [PR 5162](https://github.com/guardian/support-frontend/pull/5162) and [PR 5171](https://github.com/guardian/support-frontend/pull/5171) – both had to be reverted after merge.

In the former case, I had forgotten to make changes to the payment API, and in the second case I had tested the wrong build in CODE, missing that my changes didn’t work in support-workers.

### CODE REVIEW

**Comment by undergroundquizscene** [comment]
Tested the acquisition-events-api in CODE: deployed [build 21150](https://riffraff.gutools.co.uk/deployment/view/9e998d10-93e7-4627-8574-0c3b393fee7b) via Riff Raff (corresponding to GHA run number [1150](https://github.com/guardian/support-frontend/actions/runs/5819594204/job/15778302358?pr=5178). Sent 410 requests in quick succession to the API, observed no failed events and no out of memory errors.

**Comment by undergroundquizscene** [comment]
Tested the payment-api in CODE: deployed [build 16038](https://riffraff.gutools.co.uk/deployment/view/ae6bc96f-02fa-4520-9940-bb24c4a4cd9c) via Riff Raff which was produced by GHA run [number 4038](https://github.com/guardian/support-frontend/actions/runs/5819594190/job/15778302351?pr=5178) (`LAST_TEAMCITY_BUILD` is 6000). I sent a handful of single contributions via the checkout and checked [the logs](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/support-payment-api-CODE/log-events$3Fstart$3D1691664000000$26filterPattern$3D$26end$3D1691665019000) to confirm that everything looked normal and there were no errors.

**Comment by undergroundquizscene** [comment]
Tested support-workers in CODE by [deploying Riff Raff build 16038](https://riffraff.gutools.co.uk/deployment/view/ae6bc96f-02fa-4520-9940-bb24c4a4cd9c) which corresponds to [GHA run 4038](https://github.com/guardian/support-frontend/actions/runs/5819594189/job/15778302045?pr=5178) (`LAST_TEAMCITY_BUILD` is 12000). I submitted a handful of support-workers checkouts through the frontend and confirmed that the executions succeeded and there were no errors in the logs for the SendAcquisitionEvent step.

**Review by rupertbates — APPROVED** [review]
Hopefully when I finally get round to refactoring the acquisitions handling code to all run off a single queue this should be simpler.

**Comment by undergroundquizscene** [comment]
> Hopefully when I finally get round to refactoring the acquisitions handling code to all run off a single queue this should be simpler.

Yeah, I think that’ll help alright!

**Pull request merged**
