### PR TITLE
Fix bundle analyser gh action

### PR DESCRIPTION
**Pull request by marialani**
## What are you doing in this PR?
Our bundle analyser github action was being skipped for some time due to a conditional check in the yaml file. This conditional had been introduced to prevent certain actions running on a fork. Although, in the bundle analyser check the value we were attempting to access i.e. `github.event.pull_request.head.repo.owner.login` was undefined. This uses an alternative github context value `github.repository_owner` for the repo owner conditional checks in our github actions.

[**Trello Card**](https://trello.com/c/cEiFq7u9/964-support-frontend-fix-bundle-analyser-action)

### CODE REVIEW

**Comment by marialani** [comment]
[Support-Frontend: Fix "Bundle Analyser" action](https://trello.com/c/cEiFq7u9/964-support-frontend-fix-bundle-analyser-action)

**Comment by marialani** [comment]
@kelvin-chappell this may be of interest to you following https://github.com/guardian/payment-failure-comms/pull/95

**Review by michaelbjacobson — CHANGES_REQUESTED** [review]
Looks great, but just one small thing: you've changed single quotes to double quotes in all relevant files, but `github.repository_owner == 'guardian'` is using single quotes. It would be nice to adjust this for consistency, especially as you've done so for other strings 🙂

**Review by michaelbjacobson — APPROVED** [review]
Fab!

**Comment by marialani** [comment]
> Looks great, but just one small thing: you've changed single quotes to double quotes in all relevant files, but `github.repository_owner == 'guardian'` is using single quotes. It would be nice to adjust this for consistency, especially as you've done so for other strings 🙂

Turns out we do need to use the single quotes with string comparison here

**Pull request merged**
