### PR TITLE
January sale updates

### PR DESCRIPTION
**Pull request by walaura**
## Why are you doing this?

**🚨⚠️☢️ DO NOT MERGE UNTIL SATURDAY 🚨⚠️☢️** (or late friday, tbd)

Updates the paper sale deets to reflect the changes happening on Saturday

[**Trello Card**](https://trello.com/c/ds6NeaM0/2138-12th-of-jan-print-product-page-subscription-update)

## Changes

* New copy
* Support custom standfirsts on landing pages on flash sales
* Made the paper price descriptions shorter

## Screenshots

screenshot 2019-01-09 at 10 44 54 am
screenshot 2019-01-09 at 10 44 39 am
screenshot 2019-01-10 at 4 11 06 pm

### CODE REVIEW

**Comment by lmath** [comment]
Does that mean that the x% off label and home delivery savings being 'excluding delivery costs' are out of scope? Or they're in a future PR?

**Comment by walaura** [comment]
@lmath I'm keen to put that in but I'm confused who has to approve that to happen? What would the copy be? Also how the delivery costs are set (are they a set price, a % of the price, etc) so we can code them in

**Comment by lmath** [comment]
@walaura I don't know the answers to that but Chris might! I am just asking because I was looking at the deck on the trello card while looking at your PR.

**Comment by lmath** [comment]
Or maybe @SarahLaughton knows?

**Comment by walaura** [comment]
@lmath I know the 25% off band is in talks atm, let me rally them up

**Comment by lmath** [comment]
@walaura Aaah sorry I was just looking at the attached deck not realising that there were two trello cards with a split checklist 🙈

**Comment by walaura** [comment]
@lmath no worries!! Im emotionally invested in this too, we would very likely convert more if we portray better savings ><

**Pull request merged**
