### PR TITLE
Remove subheader copy from gifting product pages

### PR DESCRIPTION
**Pull request by worldofpablo**
## What are you doing in this PR?
This PR removes the subheader copy from the gifting pages for digital subscriptions and Guardian Weekly. 

[**Trello Card**](https://trello.com/c/JvASVIip/168-remove-hardcoded-gifting-subheaders)

## Why are you doing this?
A new gifting marketing campaign kicks off next week and the narrative is taking a different direction from the 'even while apart' concept. The old copy could clash so we're removing it.

## Is this an AB test?
- [ ] Yes
- [x] No

## Screenshots
Before:
image

image

After:
image

image

### CODE REVIEW

**Comment by worldofpablo** [comment]
[Remove hardcoded gifting subheaders](https://trello.com/c/JvASVIip/168-remove-hardcoded-gifting-subheaders)

**Comment by marialani** [comment]
> TypeScript errors decreased by 12 🥳 ESLint errors decreased by 5 😎
> 
> [typescript-monitor-action](https://github.com/guardian/typescript-monitor-action)

Well would you look at that 🥳

Did you run the ts errors script locally @TomPretty?

**Comment by TomPretty** [comment]
> > TypeScript errors decreased by 12 🥳 ESLint errors decreased by 5 😎
> > [typescript-monitor-action](https://github.com/guardian/typescript-monitor-action)
> 
> Well would you look at that 🥳
> 
> Did you run the ts errors script locally @TomPretty?

I did and the number of errors stayed the same as what's on main so I'm not quite sure what that's about! But I think we're all good to merge this one!

**Review by TomPretty — APPROVED** [review]
Looks good to me! 🚀

**Comment by marialani** [comment]
> > > TypeScript errors decreased by 12 🥳 ESLint errors decreased by 5 😎
> > > [typescript-monitor-action](https://github.com/guardian/typescript-monitor-action)
> > 
> > 
> > Well would you look at that 🥳
> > Did you run the ts errors script locally @TomPretty?
> 
> I did and the number of errors stayed the same as what's on main so I'm not quite sure what that's about! But I think we're all good to merge this one!

Yeah same, it's a bit mysterious but don't 

> > > TypeScript errors decreased by 12 🥳 ESLint errors decreased by 5 😎
> > > [typescript-monitor-action](https://github.com/guardian/typescript-monitor-action)
> > 
> > 
> > Well would you look at that 🥳
> > Did you run the ts errors script locally @TomPretty?
> 
> I did and the number of errors stayed the same as what's on main so I'm not quite sure what that's about! But I think we're all good to merge this one!

Yeah same, it might be down to a rebase as we don't explicitly having the diff for the ts history file, regardless fewer errors is always good!

**Review by marialani — APPROVED** [review]
👍

**Pull request merged**
