### PR TITLE
updates non-Aus survey url to use June 2020 survey

### PR DESCRIPTION
**Pull request by michaelbjacobson**
updates non-Aus survey url to use June 2020 survey

### CODE REVIEW

**Comment by ionamckendrick** [comment]
Would you mind adding a screenshot of the UI of the page once this is added? Think it's quite helpful. Thanks!

**Comment by michaelbjacobson** [comment]
> Would you mind adding a screenshot of the UI of the page once this is added? Think it's quite helpful. Thanks!

Will do @ionamckendrick, but at the mo it's exactly the same UI as before. The only difference is the URL it links to, and the end date.

**Comment by ionamckendrick** [comment]
@michaelbjacobson Ah yes I know, but just as sometimes we forget what the UI looks like (/people always ask me this)!

**Comment by michaelbjacobson** [comment]
@ionamckendrick please see contributions thank you page (non-Aus) screenshot below 🙂
<br>
Screenshot 2020-06-09 at 14 18 10

**Pull request merged**
