### PR TITLE
Swap out marked for snarkdown

### PR DESCRIPTION
**Pull request by marialani**
## What are you doing in this PR?
This pr removes the markdown library `marked` and replaces it with `snarkdown`.

[**Trello Card**](https://trello.com/c/NCxiJcmU/3719-swap-out-marked-for-snarkdown-on-support-frontend)

## Why are you doing this?
We rely on the marked library to parse markdown coming from the promo code tool. However we only support a limited amount of markdown styling, and don't need to include a full markdown parser on every page. Marked is about 10KiB gzipped and is one of the largest single dependencies on our landing pages whilst Snarkdown is considerably smaller.

## Is this an AB test?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by johnduffell — APPROVED** [review]
nice to get things smaller! I presume you have tested all the variations and they look fine?
👍

**Comment by GHaberis** [comment]
Woah 😮  ~10% reduction in bundle size for all affected pages, this is great to see!

**Review by GHaberis — APPROVED** [review]

**Comment by GHaberis** [comment]
> nice to get things smaller! I presume you have tested all the variations and they look fine?
> 👍

If we want to test we're correctly handling multiple variations of markdown coming from the promo code tool then I think unit tests for the function `getPromotionCopy` (exported by `promotions.jsx` and the only function that calls `getSanitisedHtml`) would be the best method to do this.

**Comment by marialani** [comment]
> > nice to get things smaller! I presume you have tested all the variations and they look fine?
> > 👍
> 
> If we want to test we're correctly handling multiple variations of markdown coming from the promo code tool then I think unit tests for the function `getPromotionCopy` (exported by `promotions.jsx` and the only function that calls `getSanitisedHtml`) would be the best method to do this.

I'd tested the variations of markdown being fed through by using some test urls and they all looked fine. Though adding unit tests for this is a very good shout, will update this branch to include some unit tests.

**Review by johnduffell — APPROVED** [review]
nice always good to have some lightweight tests for this kind of thing 👍

**Pull request merged**
