### PR TITLE
Supporter plus nudge annual

### PR DESCRIPTION
**Pull request by paul-daniel-dempsey**
Nudging component, encouraging single to monthly or annual recurring contributions
Rename test  to 'ab-singleToRecurringV2'

[**Trello Card**](https://trello.com/c/4bRuTMkx/1028-nudging-recurring-to-annual-build)

Features->
- copy change,
- differing minimum contributions,
- differing link (copy and location)

NudgeVariants

2-cohort A/B test for implementation ->
https://support.thegulocal.com/uk/contribute#ab-singleToRecurringV2=control (Monthly)
https://support.thegulocal.com/uk/contribute#ab-singleToRecurringV2=variant (Annual)

## Is this an AB test?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by paul-daniel-dempsey** [comment]
[Nudging recurring to annual - build](https://trello.com/c/4bRuTMkx/1028-nudging-recurring-to-annual-build)

**Comment by GHaberis** [comment]
@paul-daniel-dempsey the test should be renamed from `singleToRecurring` to something unique, `singleToRecurringV2` for example.

**Comment by paul-daniel-dempsey** [comment]
> @paul-daniel-dempsey the test should be renamed from `singleToRecurring` to something unique, `singleToRecurringV2` for example.

Ok will rename to V2 and other variants going forwards. Thanks.

**Review by GHaberis — APPROVED** [review]
Looks good 👍

**Pull request merged**
