### PR TITLE
Fix - Checkout Amount Querystring Bug

### PR DESCRIPTION
**Pull request by Ap0c**
### Problem

On some older browsers we've had a problem passing through the contribution amount to our checkout pages. For some reason, these browsers weren't picking up the amount from the query param in the URL, and were showing the default amount as a result. This was one of the issues dealt with in #465 for the Samsung Browser. It has subsequently shown up in older versions of Firefox.

### What's going on?

This was an interesting one to track down. This screenshot explains the problem:

querystring-madness

The `URLSearchParams` constructor doesn't handle querystrings that include the leading question mark `?`. This is a problem because that's what `window.location.search` returns, which is what we happen to be using in our `getQueryParameter` helper.

It seems like the spec wasn't specific as to what should happen here, and was subsequently updated to mandate that the leading `?` be handled. However, both [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1268361) and Chromium (which is what the Samsung Browser is based on) had already implemented the standard. They have both been updated to fix this, but older versions still suffer from the problem.

### Solution

I've switched our usages of `URLSearchParams(window.location.search)` to use `URL(window.location).searchParams` instead. By getting our URLSearchParams object via the URL interface, instead of from the URLSearchParams constructor, we sidestep the problem, as seen here:

querystring-solution

Presumably when picking apart a full URL, the `?` was usually expected, so it was handled from the start.

[**Trello Card**](https://trello.com/c/xskTe9Ak/1322-ff-48-not-passing-through-contribution-amount-to-checkout)

## Changes

- Updated two usages of the `URLSearchParams` constructor being used in concert with `window.location.search` to use the `URL.searchParams` interface instead.

### CODE REVIEW

**Comment by jacobwinch** [comment]
Great work @Ap0c 👍

**Comment by Ap0c** [comment]
@davidfurey for the more recent Samsung browsers, yes (5.x I believe @JustinPinner?). For the much older ones, sadly not, because they were broken in multiple different ways.

**Comment by johnduffell** [comment]
great detective work, however my question would be why do we default to the highest amount?  we should default to not letting them contribute if the amount is missing when it should be present to avoid this kind of repetitional damage

**Comment by Ap0c** [comment]
@johnduffell we should default to the... default amount, which isn't typically the highest. For example, we offer preset amounts of £25, £50, £100 and £250 for one-off contributions, with £50 being the preselected one in that list. If someone comes through the to the checkout page with the contribution amount somehow missing, we fallback to offering the preselected amount.

That said, I think it's a fair question as to why we do this, and why we don't use the minimum amount. After all, someone should only end up on the checkout page without a chosen amount if something's gone wrong.

**Comment by johnduffell** [comment]
thanks for the detaled background!  Agree with defaulting to the safest value if it's an easy fix.  Better still would be to show an error and notify sentry so we can address it before someone complains.

**Comment by Ap0c** [comment]
Ok, I've put a card in to review it.

**Comment by johnduffell** [comment]
oh yeah PS I'm not disapproving this PR, it's great!  I just want more 🚀

**Pull request merged**
