### PR TITLE
[US launch 🚀]   Copy changes

### PR DESCRIPTION
**Pull request by svillafe**
## Why are you doing this?

To put everything in place before launching.

[**Trello Card**](https://trello.com/c/Cb1JZh4N/956-contributions-landing-page-review)

## Screenshots
|   Breakpoints     | Before | After |
|-----------------|---------|-------|
| Mobile (from: `320px`) | mobileold |    mobilenew   |
|    Phablet (from:`660px`)     |    phabletnew    |  phablet-new |
|     Tablet (from:`740px`)     |  tablet-old      |    tablet-new  |
|    Desktop (from:`980px`)       |     desktop-old  | desktop-new     |
|    LeftCol (from:`1140px`)  |   leftcol-old   |   leftcol-new    |
|    Wide (from:`1300px`)  |    wide-old  |    wide-new|

### CODE REVIEW

**Comment by svillafe** [comment]
cc: @Amohkhan

**Comment by Amohkhan** [comment]
👍

**Comment by svillafe** [comment]
Post deploy tests running locally

**Comment by svillafe** [comment]
@prout-bot It failed the build now it is being deployed

**Pull request merged**
