### PR TITLE
Created scss file for `/uk`

### PR DESCRIPTION
**Pull request by svillafe**
## Why are you doing this?

To send to the client only the CSS that we use in `/uk`.

[**Trello Card**](https://trello.com)

## Changes

* Creates `supportLandingStyles.scss`
* Deleted unnecessary argument for the Scala controller of the support landing page. 
* Renamed mainBundleJs to mainJSBundle

## Impact
| Before | After  |
|--------|--------|
| 73 418 | 38 382 |

## Screenshots
| Before | After  |
|--------|--------|
|cssbeforeuktoday  |cssafteruktoday|

### CODE REVIEW

**Comment by Ap0c** [comment]
I think you might need `contribLegal` as well:

contrib-legal

**Comment by svillafe** [comment]
@Ap0c added here: 97e57c5

**Comment by Ap0c** [comment]
`subscriptionBundle.scss`? Something's a bit weird here. The main and bulleted headings should be bold, and there's some bleed from the bullet points.

sub-bundle

**Comment by svillafe** [comment]
We have tried the PayPal flow in the US with a real user with @michaelwmcnamara and is working.

**Pull request merged**
