### PR TITLE
Update V2 Thank You Page Modules and Footer copy

### PR DESCRIPTION
**Pull request by marialani**
## What are you doing in this PR?
This updates the copy for the modules and footer on the Supporter Plus thank you page. 

Please see [this section](https://docs.google.com/document/d/1YBqE24iC2LZpdY_wfwLepgdN3zObpYe793DmAgdp_Pg/edit?hl=en-GB&forcehl=1#heading=h.3kb9nsnt6q24) of the copy update dock for the required copy combinations. Until we test the live checkout you can view these copy updates [here](https://62e115310aef0868687b2322-uiedzbkcay.chromatic.com/) in storybook. 

[**Trello Card**](https://trello.com/c/wIJdGCxX/730-show-appropriate-copy-on-thank-you-page-for-v2-checkout)

## Screenshots
Please click through the supporter plus thank you page screens in [storybook](https://62e115310aef0868687b2322-uiedzbkcay.chromatic.com/) to view these updates.

### CODE REVIEW

**Comment by marialani** [comment]
[Show appropriate Copy on Thank you page for V2 checkout](https://trello.com/c/wIJdGCxX/730-show-appropriate-copy-on-thank-you-page-for-v2-checkout)

**Comment by GHaberis** [comment]
@marialani just looking at the Storybook Stories (which are super helpful!) and I can see the "Download the app" module for Recurring Contributors below the threshold: https://62e115310aef0868687b2322-uiedzbkcay.chromatic.com/?path=/story/screens-supporter-plus-thank-you-page-rest-of-world--recurring-signed-in&args=amountIsAboveThreshold:false

**Comment by marialani** [comment]
> @marialani just looking at the Storybook Stories (which are super helpful!) and I can see the "Download the app" module for Recurring Contributors below the threshold, see [here](https://62e115310aef0868687b2322-uiedzbkcay.chromatic.com/?path=/story/screens-supporter-plus-thank-you-page-rest-of-world--recurring-signed-in&args=amountIsAboveThreshold:false). I was expecting it to be only visible for SupporterPlus purchases.

Ah we don't have any logic in at the moment that specifies it'll only show for recurring types. I'll have a quick check in with Helene and update this

**Comment by marialani** [comment]
> @marialani just looking at the Storybook Stories (which are super helpful!) and I can see the "Download the app" module for Recurring Contributors below the threshold, see [here](https://62e115310aef0868687b2322-uiedzbkcay.chromatic.com/?path=/story/screens-supporter-plus-thank-you-page-rest-of-world--recurring-signed-in&args=amountIsAboveThreshold:false). I was expecting it to be only visible for SupporterPlus purchases.

You're completely right here, just had a check-in with Helene. We didn't have logic in for this but have just added in a conditional to ensure we only show it above the threshold

**Review by GHaberis — APPROVED** [review]
Looking good 👍

**Pull request merged**
