### PR TITLE
Payment Flow: Positioning images in bubbles

### PR DESCRIPTION
**Pull request by regiskuckaertz**
## Why are you doing this?

The new design has a background with images inset into circles. We wanted these images to respect the user's device constraints, something SVG does not provide with the `image` element. There are two solutions for this:

- in CSS, using `image-set` (the syntax is similar to the `srcset` attribute)
- in HTML, using `` elements

I went for the latter because there is existing infrastructure; but ideally this should be moved into the CSS. Anyway, images are in the DOM and are set centred in the canvas, then offset either left or right using a translation.

At the moment I am using the same image all the time, but the ones provided by @Amohkhan should be inserted into the grid and used here, with appropriate sizes (the ones I used are random).

[**Trello Card**](https://trello.com/c/LZUMRF8W/815-npf-positioning-images-in-bubbles-i-cant-believe-i-wrote-that)

## Screenshots

screen shot 2018-09-04 at 11 29 42
screen shot 2018-09-04 at 10 57 58

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
@Ap0c @rupertbates there is a solution for images in bubbles respecting the device display size.

**Comment by regiskuckaertz** [comment]
@Amohkhan can you upload the images (best resolution) to the grid? Then we can create variants for mobile/desktop.

**Comment by regiskuckaertz** [comment]
Discussion with @ionamckendrick led to the conclusion that the images will be left out for the test, so I'll replace them with plain circles in the SVG

**Comment by regiskuckaertz** [comment]
I think I'm going to merge this anyway, so that it is part of the repo history. I can undo the images in the follow-up PR, as I have to apply design changes anyway. A 👍 would be welcome!

**Comment by ionamckendrick** [comment]
@regiskuckaertz I think this is a good idea, as we are likely to want to use images in a future test. I imagine this makes things a lot easier / avoids repetition of work?! Thanks.

**Comment by regiskuckaertz** [comment]
@ionamckendrick Yes! And I also made improvements to the SVGs that I do not want to lose.

**Pull request merged**
