### PR TITLE
upgrade java 8 => java 11 for payment-api

### PR DESCRIPTION
**Pull request by jamesgorrie**
## What are you doing in this PR?
Upgrading the `payment-api` to Java 11.

[**Trello Card**](https://trello.com/c/zOnD5RZ4/1587-update-java-version-in-support-payment-api-from-8-to-11)

## Update

With the update to Java 11, [the `jaxb` libraries were removed with the Java EE modules](https://openjdk.org/jeps/320). There's some good literature out there - [this article](https://www.jesperdj.com/2018/09/30/jaxb-on-java-9-10-11-and-beyond/) sums it up nicely.

We have now added these libraries as dependencies.

## Discovery 

When running the `AmazonPayBackend.makePayment` the [`getOrderReference`](https://github.com/guardian/support-frontend/blob/main/support-payment-api/src/main/scala/backend/AmazonPayBackend.scala#L71C27-L71C44) was throwing the error:
`model.amazonpay.AmazonPayApiError: Encountered marshalling error while marshalling data`
```xml
<AmazonXML xmlns="http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01">
  <!-- ...XML -->
</AmazonXML>
```

Unfortunately in `PROD` this XML was the `AmountNotSet` error, which led us to try and fix that, where as the important piece of the error was **`Encountered marshalling error`**. 

Digging into the `aws-pay-java-sdk`, you can see the error comes from [their `marshalXML` method](https://github.com/amzn/amazon-pay-sdk-java/blob/master/src/com/amazon/pay/response/parser/Parser.java#L223).

Digging deeper, the [`JAXBException`](https://github.com/amzn/amazon-pay-sdk-java/blob/master/src/com/amazon/pay/response/parser/Parser.java#L222) that the `AmazonClientException` is derived from is:
```
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
```

## Why are you doing this?
We need to start using Java 11 to allow us to upgrade further dependencies, especially if there are security vulnerabilities.

[We had tried this previously](https://github.com/guardian/support-frontend/pull/5317), but had reverted in fear that there was a conflict between `amazon-pay-java-sdk` and Java 11.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
This currently throws the `AmountNotSet:The seller has not set the amount for the Order Reference` error, so we should not merge.

**Comment by jamesgorrie** [comment]
I have managed to dig out the underlaying issue between Java 8 and Java 11 as:

```
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
```

**Comment by jamesgorrie** [comment]
This has been deployed and tested on `CODE`.

**Review by LAKSHMIRPILLAI — APPROVED** [review]

**Review by LAKSHMIRPILLAI — APPROVED** [review]

**Comment by jamesgorrie** [comment]
Screenshot 2023-11-20 at 10 18 02

Tested on CODE

**Comment by jamesgorrie** [comment]
We've been seeing successful payments since deploy, so all is 🟢 

Screenshot 2023-11-20 at 13 49 36

**Pull request merged**
