### PR TITLE
Restrict egress traffic to allow only https

### PR DESCRIPTION
**Pull request by svillafe**
## Why are you doing this?

To ensure that all the outgoing connections from our EC2 instances are under `https`

[**Trello Card**](https://trello.com/c/05jyLRpI/1015-check-that-all-outgoing-connections-from-support-frontend-and-membership-frontend-use-https-or-other-encrypted-connection)

## Changes

* Add an egress policy to `cfn.yaml`

### CODE REVIEW

**Comment by davidfurey** [comment]
This looks good to me but @adamnfish might like to comment

**Comment by svillafe** [comment]
Tested in CODE:

| Flow | Status |
|------|--------|
| Regular contribution Stripe  |        |
| Regular contribution PayPal  |        |
| One-off contribution Stripe  |        |
| One-off contribution PayPal  |        |

**Comment by svillafe** [comment]
Similar PR in membership: https://github.com/guardian/membership-frontend/pull/1744

**Comment by adamnfish** [comment]
Great!

Bear in mind, traffic within the private network won't necessarily have to be encrypted and yuo might be making TCP calls within the network that this change will break. If it works for you though, then this is a great way of enforcing the Right Way.

**Pull request merged**
